config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users

  root :to => 'projects#index'

  resources :projects do
   resources :tickets
  end


  namespace :admin do
    root :to => "base#index"
    resources :users
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name

  has_many :tickets, dependent: :delete_all
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :description, :title, :user
  validates_presence_of :title
  validates :description, :presence => true,
                          :length => { :minimum => 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin #Make this work for app, but really in this app?!

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :authorize_admin!

  def index
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all(:order => "email")
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    set_admin
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been created."
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    set_admin
    if @user.update_attributes(params[:user])
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def set_admin
      @user.admin = params[:user][:admin] == "1"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
    def authorize_admin!
      authenticate_user!
      unless current_user.admin
        flash[:alert] = "You must be an admin to do that."
        redirect_to root_path
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin!, except: [:index, :show]

  def index
    @projects = Project.all
  end


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project,
      notice: "Project has been created."

    else
      flash[:notice] = "There was an issue saving your project."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      redirect_to @project,
      notice: "Project has been updated."

    else
      flash[:notice] = "There was an issue updating your project."
      render "edit"
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path,
    notice: "#{@project.name} has been deleted!"
  end

  private

    def find_project
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_project
  before_filter :find_ticket, :only => [:show,
                                        :edit,
                                        :update,
                                        :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render :action => "edit"
    end
  end

  def show
  end

  def destroy
    @ticket.destroy
    redirect_to project_path(@project),
    notice: "#{@ticket.title} has been deleted!"
  end

  private

    def find_project
      @project = Project.find(params[:project_id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end

    def find_ticket
      @ticket = @project.tickets.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The ticket you were looking for could not be found."
      redirect_to project_path(@project)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %>
Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>

<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>

<%= link_to "Edit User", edit_admin_user_path(@user) %>

<%= link_to "Delete User", admin_user_path(@user), :method => :delete,
:confirm => "Are you sure you want to delete this user?" %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<h1><%= link_to "Ticketee", root_path %></h1>
<nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{@title} -" if @title.present? %> Ticketee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/flash", locals: {flash: flash} %>

  <%= render partial: "layouts/header" %>
  <%= admins_only do %>
    <%= link_to "Admin", admin_root_path %><br>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<% @title = " Edit Project " %>

<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

<%= admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<% @title = " New Project " %>

<h2>New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% @title = @project.name + " - Projects " %>

<h2><%= @project.name %> Project</h2>

<%= admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", @project, method: :delete, confirm: "Arem you sure you want to delete #{@project.name}?" %>
<% end %>


<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for([@project, @ticket]) do |f| %>
  <% if @ticket.errors.any? %>
    <% @ticket.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<% @title = " Edit Ticket " %>

<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<% @title = " New Ticket " %>

<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<% @title = @ticket.title + " - Tickets " %>

<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <br />
  <small>Created by <%= @ticket.user.email %></small>
  <%= simple_format(@ticket.description) %>
</div>

<%= link_to "Edit Ticket", edit_project_ticket_path(@project, @ticket) %>
<%= link_to "Delete Ticket", [@project, @ticket], method: :delete, confirm: "Arem you sure you want to delete #{@ticket.title}?" %>


<%= link_to "New Ticket", new_project_ticket_path(@project) %>